"""DSL decomposer — translates a group definition into primitive steps.

This is the second LLM-assisted step in the Build phase (runs per group).
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from src.decomposer.llm_client import LLMClient
from src.models.control import ControlFile
from src.models.decomposition import GroupDefinition
from src.models.dsl import ALLOWED_PRIMITIVE_TYPES, DSLPlan
from src.utils.filesystem import ensure_dir, load_yaml
from src.utils.logging import get_logger

log = get_logger(__name__)

# JSON Schema enforced via structured output
_DSL_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "type": {"type": "string", "enum": sorted(ALLOWED_PRIMITIVE_TYPES)},
                    "output_alias": {"type": "string"},
                },
                "required": ["id", "type"],
                "additionalProperties": True,
            },
        }
    },
    "required": ["steps"],
    "additionalProperties": False,
}


def _load_system_prompt() -> str:
    prompt_path = Path(__file__).parent / "prompts" / "decompose_dsl.txt"
    return prompt_path.read_text(encoding="utf-8").strip()


def _build_user_prompt(control: ControlFile, group: GroupDefinition) -> str:
    """Build the user-facing prompt for DSL generation."""
    ctrl_data = control.model_dump()
    grp_data = group.model_dump()

    primitives_doc = "\n".join(f"  - {p}" for p in sorted(ALLOWED_PRIMITIVE_TYPES))

    return (
        f"Generate the DSL steps for the following execution group.\n\n"
        f"Control definition:\n```yaml\n{yaml.dump(ctrl_data, default_flow_style=False, allow_unicode=True)}\n```\n\n"
        f"Group to decompose:\n```yaml\n{yaml.dump(grp_data, default_flow_style=False, allow_unicode=True)}\n```\n\n"
        f"Supported primitive types:\n{primitives_doc}\n\n"
        "Emit ONLY the JSON steps array."
    )


def decompose_dsl(
    control: ControlFile,
    group: GroupDefinition,
    controls_dir: Path,
    llm_client: LLMClient,
    force: bool = False,
) -> DSLPlan:
    """Generate (or load) the DSL plan for a single execution group.

    Args:
        control:       Parsed ControlFile.
        group:         The specific group to decompose.
        controls_dir:  Root controls/ directory.
        llm_client:    Configured LLM client.
        force:         If True, delete existing DSL and regenerate.

    Returns:
        A validated DSLPlan.
    """
    dsl_path = controls_dir / control.control.id / "groups" / group.id / "dsl.yaml"

    if dsl_path.exists() and not force:
        log.info(
            f"[{control.control.id}/{group.id}] dsl.yaml exists — loading (skip LLM)."
        )
        raw = load_yaml(dsl_path)
        return DSLPlan.model_validate(raw)

    if force and dsl_path.exists():
        dsl_path.unlink()
        log.info(
            f"[{control.control.id}/{group.id}] --force: deleted existing dsl.yaml."
        )

    log.info(f"[{control.control.id}/{group.id}] Calling LLM to generate DSL ...")

    system_prompt = _load_system_prompt()
    user_prompt = _build_user_prompt(control, group)

    raw_response = llm_client.call_structured(system_prompt, user_prompt, _DSL_SCHEMA)

    now = datetime.now(timezone.utc).isoformat()
    plan = DSLPlan(
        control_id=control.control.id,
        group_id=group.id,
        generated_at=now,
        generator="llm",
        steps=raw_response["steps"],
    )

    # Write
    ensure_dir(dsl_path.parent)
    data = plan.model_dump()
    data["_comment"] = (
        "Generated by dsl_decomposer. MANUALLY CORRECTABLE — "
        "will not be overwritten if this file exists."
    )
    with open(dsl_path, "w", encoding="utf-8") as fh:
        yaml.dump(
            data, fh, default_flow_style=False, allow_unicode=True, sort_keys=False
        )

    log.info(f"[{control.control.id}/{group.id}] dsl.yaml written → {dsl_path}")
    return plan
